- hosts: localhost
  gather_facts: false
  tasks:
  - name: Download Tower Setup file
    unarchive:
      src: https://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-3.2.8.tar.gz
      dest: /root/
      remote_src: yes
    when: setup_tower == "yes"

  - name: Create template file
    template:
      src: ./tower_template_inventory.j2
      dest: /root/ansible-tower-setup-3.2.8/inventory
    when: setup_tower == "yes"

  - name: Run Ansible Tower setup
    shell: /root/ansible-tower-setup-3.2.8/setup.sh
    async: 3600
    poll: 36
    when: setup_tower == "yes"

  - name: Append inventory file
    blockinfile:
      path: /root/ansible-tower-setup-3.2.8/inventory
      block: |
        [isolated_group_osp]
        workstation-{{OSP_GUID}}.rhpds.opentlc.com ansible_user='cloud-user' ansible_ssh_private_key_file='~/.ssh/openstack.pem' ansible_ssh_common_args='-o StrictHostKeyChecking=no'
        [isolated_group_osp:vars]
        controller=tower
      state: present
    when: setup_tower == "yes"

  - name: Run Ansible Tower setup
    shell: /root/ansible-tower-setup-3.2.8/setup.sh
    async: 3600
    poll: 36
    when: setup_tower == "yes"
  - name: Install tower-cli
    package: 
      name: python2-ansible-tower-cli.noarch
      state: present
    when: setup_tower == "yes"
