- name: Create CI CD Workflow
  command: |
    tower-cli workflow create -n {{workflow_template_name}} --organization {{org_name}} -h "https://tower1.{{tower_GUID}}.example.opentlc.com" -u "{{user_name}}" -p "{{password}}"

- name: Create workflow schema 
  template:
    src: workflow.j2
    dest: /tmp/workflow.yml

- name: Create workflow using schema
  command: |
    tower-cli workflow schema {{workflow_template_name}} @/tmp/workflow.yml -h "https://tower1.{{tower_GUID}}.example.opentlc.com" -u "{{user_name}}" -p "{{password}}"

